#!/bin/bash
name=inary
version=master
release=1
description="Package manager for Sulin Project"
arch=(i686 x86_64)
url='https://sulinos.gitlab.io'
license=('GPL')
source=(https://gitlab.com/sulincix/inary-new/-/archive/master/inary-new-master.zip)
md5sums=(SKIP)

cd inary-new-master

build(){
    rm -rf build || true
    mkdir -p build
    meson build -Dtools=true
    ninja -C build
}
install(){
    DESTDIR=$installdir ninja install -C build
}

