#!/bin/bash
name=ymp
version=master
release=1
description="Package manager for Turkish"
arch=(i686 x86_64)
url='https://gitlab.com/turkman/'
license=('GPL')
source=(https://gitlab.com/turkman/devel/sources/ymp/-/archive/master/ymp-master.zip)
md5sums=(SKIP)
group=(sys.apps)
uses=(libarchive libcurl)
depends=(readline ncurses glib)
libarchive_depends=(libarchive)
libcurl_depends=(curl)

cd ymp-master

setup(){
    meson setup build --prefix=/usr \
        -Ddoc=true \
        -Dshared=true \
        -Dscripts=true \
        -Dlibbrotli=false \
        $(use_opt libarchive "" "-Dlibarchive=false") \
        $(use_opt libcurl "" "-Dlibcurl=false")
}

build(){
    ninja -C build
}
install(){
    DESTDIR=$(DESTDIR) ninja -C build install
}

