#!/bin/bash
export LANG=C
function detect_dependency(){
    ### find elf file list
    ldd "$1" |& grep "=>" | cut -f3 -d" " | sort | uniq | \
        while read line ; do
        ### find package names
        ymp search --file $line
    done
}
for arg in $@ ; do
    if [[ -f "$arg" ]] ; then
        detect_dependency "$arg"
    else
        cat /var/lib/ymp/files/"$arg" | while read line ; do
            detect_dependency /${line:41}
        done
    fi
done
