#!/bin/sh
if [ ! -d "$1" ] ; then
    echo "ymp-chroot: missing rootfs"
    exit 1
fi
for i in /dev /sys /proc /run
do
	mkdir -p $1/$i 2>/dev/null || true
	umount -R -lf $1/$i &>/dev/null || true
	mount --bind $i $1/$i
done
chroot $*
q=$?
for i in /dev /sys /proc /run ; do
    while umount -lf -R $1/$i 2>/dev/null ; do
        :
    done
done
exit $q
