#!/usr/bin/env bash
set -e
if [[ $UID -eq 0 ]] ; then
    echo "Error: root build is not allowed" >/dev/stderr
    exit 1
fi
if [[ "$1" == "--ignore-dependency" ]] ; then
    ignore=1
    shift
fi
for dir in $@ ; do
    fdir=$(realpath $dir)
    echo "BUILD: $fdir"
    if [[ -f "$fdir/ympbuild" ]] ; then
        exec ymp build --sandbox --verbose --allow-oem --shared="$fdir" --use="all" "$fdir" ${ignore:+--ignore-dependency}
    fi
done

