#!/usr/bin/env bash
set -e
if [[ $UID -eq 0 ]] ; then
    echo "Error: root build is not allowed" >/dev/stderr
    exit 1
fi
for dir in $@ ; do
    fdir=$(realpath $dir)
    echo "BUILD: $fdir"
    if [[ -f "$fdir/ympbuild" ]] ; then
        exec ymp --sandbox --verbose --allow-oem --shared="$fdir" --use="all" build "$fdir"
    fi
done

