#!/bin/bash
name=hello
version=2.10
release=1
description="Prints Hello World and more"
arch=(i686 x86_64)
url='https://gnu.org'
license=('GPL')

source=(https://ftp.gnu.org/gnu/hello/$name-$version.tar.gz)
md5sums=('6cd0ffea3884a4e79330338dcc2987d6')

build(){
    cd "$name-$version"
    ./configure --prefix=/usr
    make
}
package(){
    cd "$name-$version"
    make install DESTDIR=$installdir
}

